
# GLOBAL OPERATION PARAMETERS
loop_rate: 100                    # desired rate for joint state updates. actual rate may be less depending on number
                                  # of dynamixels on each port
control_mode: position            # control mode, either 'position', 'velocity', or 'effort'
disable_torque_on_shutdown: true  # with this enabled the motors will switch off when the controller closes
ignore_input_velocity: false      # ignore input velocity commands in position mode (no profile velocity)
diagnostics_rate: 1               # rate to publish diagnostic information
dataport_rate: 1                  # rate to read from dynamixel external dataports

# The below values are used as global defaults and are applied for each servo unless overridden in the entry for the servo below
global_max_vel: 5.0               # maximum joint speed (rad/s) (in position or velocity control)
global_torque_limit: 1.0          # maximum motor torque for all modes, given as a fraction of rated max (0-1)


# PORT AND SERVO CONFIGURATIONS
ports:

  # PORT LIST
  - name: Port_1               # name for this port in config
    device: /dev/ttyACM0       # serial device this port will communicate on
    baudrate: 1000000          # baudrate in use 9600
    use_legacy_protocol: false # wether to use new 2.0 protocol (false) or legacy 1.0 protocol (true)
    group_read_enabled: true   # specify whether to use group comms for reading
    group_write_enabled: true  # specify whether to use group comms for writing
    servos:
        # SERVO LIST FOR THIS PORT
        - id: 1                # (ID set in servo eeprom, must be unique on this port)
          joint_name: roll  # (MUST BE UNIQUE ACROSS ALL PORTS)
          #
          # The three values below are mandatory, they define the orientation and zeroing of the dynamixel:
          #
          zero_pos: 2048       # initial (0 rad) servo position (in raw encoder count)
          min_pos: 0           # minimum servo position (in raw encoder count)
          max_pos: 4095        # maximum servo position, Note when MIN > MAX ROTATION IS REVERSED
          #
          # The below arguments are all optional and override the global values:
          #
          max_vel: 3.0         # maximum joint speed (rad/s) (in position or velocity control)
          torque_limit: 1.0    # maximum motor torque for all modes, given as a fraction of rated max (0-1)

        - id: 2
          joint_name: tilt
          zero_pos: 2048
          min_pos: 0
          max_pos: 4095
          max_vel: 3.0         # maximum joint speed (rad/s) (in position or velocity control)
          torque_limit: 1.0    # maximum motor torque for all modes, given as a fraction of rated max (0-1)